config/routes.rb
Sidemura::Application.routes.draw do  

  resources :informixes
  
  resources :motivos
  
  resources :convocatorias
 
  resources :concursos  

  resources :categorias  
  
  resources :titulaciones
  
  get "solicitudes/verificar/:id", to: "solicitudes#verificar_solicitud"
  
  get "solicitudes/verificar", to: "solicitudes#verificar"
 
  get "solicitudes/actualizar_concurso", to: "solicitudes#actualizar_concurso"

  post "solicitudes/verificar", to: "solicitudes#validar"

  post "solicitudes/rechazar", to: "solicitudes#rechazar"
  
  get "solicitudes/ficheros", to: "solicitudes#ficheros"

  post "solicitudes/ficheros", to: "solicitudes#add_ficheros"
  
  post "solicitudes/add_pdf", to: "solicitudes#add_pdf"
  
  get "solicitudes/imprimir/:grupo/:concurso/:turno/:estado", to: "solicitudes#imprimir"

  get 'solicitudes/actualiza_municipios/:id', to: 'solicitudes#actualiza_municipios'

  get 'solicitudes/actualiza_titulaciones/:id', to: 'solicitudes#actualiza_titulaciones'
  
  get 'solicitudes/actualiza_tasas/:id', to: 'solicitudes#actualiza_tasas'

  get 'solicitudes/actualiza_codigo_categoria/:id/:subid', to: 'solicitudes#actualiza_codigo_categoria'
  
  resources :solicitudes
    
  resources :tipologias
  
  resources :municipios 

  resources :provincias
 
  resources :submenus
  
  resources :menus  
  
  resources :usuarios

  get "dashboard/", to: "dashboard#index"

  get "dashboard/real", to: "dashboard#real"

  get "dashboard/charts", to: "dashboard#charts"
  
  get "/login", to: "sesiones#new"
  
  post "/login", to: "sesiones#create"
  
  delete "/login", to: "sesiones#destroy"

  root 'dashboard#index'

  

end

app/models/motivo.rb
class Motivo < ActiveRecord::Base      
  scope :activo, -> { where(activo: true) }
      
    validates :denominacion, presence: true
    
end

app/controllers/motivos_controller.rb
class MotivosController < ApplicationController
  before_action :requiere_autenticacion!  
  before_filter :set_motivo, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:create]

  def index
    @motivos = Motivo.activo.page params[:page]
    respond_to do |format|
      format.html
      format.json { render json: MotivosDatatable.new(view_context) }
    end
  end
  
  def new
    @motivo = Motivo.new
  end
  
  def edit
  end
  
  def create
    @motivo = Motivo.new(motivo_params)
    if @motivo.save
      flash[:notice] = "Motivo añadida correctamente"
      redirect_to motivos_path
    else
      flash[:alert] = "Hubo un error al añadir el Motivo"
      render "new"
    end
  end

  def update
    if @motivo.update(motivo_params)
      flash[:notice] = "Motivo modificada correctamente"
      redirect_to motivos_path
    else
      flash[:alert] = "Hubo un error al modificar el Motivo"
      render "edit"
    end
  end
  
  def destroy
    @motivo.activo = false
    @motivo.save
    flash[:notice] = "Motivo borrada correctamente"
    redirect_to motivos_path
  end
  
  private
  def motivo_params
    params.require(:motivo).permit(:denominacion, :activo)
  end
  
  def set_motivo
    @motivo = Motivo.activo.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Vaya, parece que ha habido un error al buscar esa Motivo"
    redirect_to motivos_path
  end
end

app/helpers/motivos_helper.rb
module MotivosHelper
  def boton_motivo
    Submenu.where(enlace: "/motivos").last.icono
  end
end

app/views/motivos/_boton_atras.html.erb
<div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to motivos_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Nuevo Motivo
          </button>
        <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/motivos/_boton_nuevo.html.erb
<div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to new_motivo_path do %>
        <button class="btn btn-primary btn-sm">
          <i class="<%= boton_motivo %>"></i>
          Nuevo Motivo
        </button>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/motivos/_errores.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %>
    <% if @motivo.errors.any? %>
      <div id="error_explanation">
        <%= pluralize(@motivo.errors.count, "error") %>
          debe corregirse:
        <ul>
          <% @motivo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

app/views/motivos/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header blue-background">
        <% if params[:action] == "new" %>
        <div class="title">Nuevo Motivo</div>
        <% else %>
        <div class="title">Editar Motivo</div>
        <% end %>
        <div class="actions">
          <a href="#" class="btn box-collapse btn-xs btn-link"><i></i>
          </a>
        </div>
      </div>
      <div class="box-content">        
        <%= form_for @motivo, :html => {:novalidate => 'novalidate', class: "form form-horizontal validate-form"} do |f| %>
        
          
            
              
                
                <div class="form-group">
                  <%= f.label :denominacion, class: "control-label col-sm-3 col-sm-3" %>
                  <div class="col-sm-4 controls">
                    <%= f.text_field :denominacion, class: "form-control", placeholder: "Introduce el denominacion", "data-rule-required" => "true", "data-rule-minlength" => "2" %>
                  </div>
                </div>
                
              
            
          
        
          
            
              
            
          
        
        <div class="form-actions">
          <div class="row">
            <div class="col-sm-9 col-sm-offset-3">
              <%= f.submit class: "btn btn-primary" do %>
              <i class="icon-save"></i>            
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/motivos/_motivos.html.erb
<div class="row">
  <div class="col-sm-12">
    <div style="margin-bottom:0;" class="box bordered-box blue-border">
      <div class="box-header blue-background">
        <div class="title">Listado de Motivos</div>
        <div class="actions">
          <a href="#" class="btn box-collapse btn-xs btn-link"><i></i>
          </a>
        </div>
      </div>
      <div class="box-content box-no-padding">
        <div class="responsive-table">
          <div class="scrollable-area">

            <table id="motivos" class='data-table-column-filter table table-bordered table-striped dataTable' data-source="<%= motivos_url(format: "json") %>">
                   <!-- we need thead because of ordering controls -->
                   <thead>
                <tr>
                  <th width="10%">#</th>
                  
                    
                      <th>denominacion</th>
                    
                  
                    
                  
                  <th width="11%">Acciones</th>
                </tr>             
              </thead>
              <tbody>
                <% @motivos.each do |e| %>
                <tr>
                  <td width="10%"><%= e.id %></td>
                  
                    
                    
                      <td><%= e.denominacion%></td>
                      
                    
                    
                    
                    
                    
                    
                  <td width="11%">
                    <div class="text-right">                     
                      <a id="Editar" href="/motivos/<%= e.id %>/edit" class="btn btn-success btn-xs"> 
                         <i class="icon-edit"></i>
                      </a> 
                      <a rel="nofollow" id="Borrar" href="/motivos/<%= e.id %>" data-method="delete" data-confirm="¿Seguro que quieres borrar este Motivo?" class="btn btn-danger btn-xs">
                         <i class="icon-remove"></i>
                      </a>
                    </div>

                  </td>
                </tr>
                <% end %>
              </tbody>       
              <tfoot>
                <tr>
                  <th>Id</th>
                  
                    
                      <th>denominacion</th>
                    
                  
                    
                  
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/motivos/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-edit"></i>
        <span>Motivos</span>
      </h1>
      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <%= render 'errores' %>
  <div class="box">
    <div class="box-content">
      <div class="btn-toolbar">
        <div class="btn-group dropdown">

          <%= link_to motivos_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Atrás
          </button>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>
  <%= render 'form' %>

app/views/motivos/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-table"></i>
        <span>Motivos</span>
      </h1>

      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <%= render "layouts/mensajes" %>
  <%= render "boton_nuevo" %>
</div>
  <%= render 'motivos' %>

app/views/motivos/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-edit"></i>
        <span>Motivos</span>
      </h1>
      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>  
  <%= render 'errores' %>
  <div class="box">
    <div class="box-content">
      <div class="btn-toolbar">
        <div class="btn-group dropdown">

          <%= link_to motivos_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Atrás
          </button>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>
  <%= render 'form' %>