config/routes.rb
Sidemura::Application.routes.draw do  

  resources :informixes
  
  resources :motivos
  
  resources :convocatorias
 
  resources :concursos  

  resources :categorias  
  
  resources :titulaciones
  
  get "solicitudes/verificar/:id", to: "solicitudes#verificar_solicitud"
  
  get "solicitudes/verificar", to: "solicitudes#verificar"
 
  get "solicitudes/actualizar_concurso", to: "solicitudes#actualizar_concurso"

  post "solicitudes/verificar", to: "solicitudes#validar"

  post "solicitudes/rechazar", to: "solicitudes#rechazar"
  
  get "solicitudes/ficheros", to: "solicitudes#ficheros"

  post "solicitudes/ficheros", to: "solicitudes#add_ficheros"
  
  post "solicitudes/add_pdf", to: "solicitudes#add_pdf"
  
  get "solicitudes/imprimir/:grupo/:concurso/:turno/:estado", to: "solicitudes#imprimir"

  get 'solicitudes/actualiza_municipios/:id', to: 'solicitudes#actualiza_municipios'

  get 'solicitudes/actualiza_titulaciones/:id', to: 'solicitudes#actualiza_titulaciones'
  
  get 'solicitudes/actualiza_tasas/:id', to: 'solicitudes#actualiza_tasas'

  get 'solicitudes/actualiza_codigo_categoria/:id/:subid', to: 'solicitudes#actualiza_codigo_categoria'
  
  resources :solicitudes
    
  resources :tipologias
  
  resources :municipios 

  resources :provincias
 
  resources :submenus
  
  resources :menus  
  
  resources :usuarios

  get "dashboard/", to: "dashboard#index"

  get "dashboard/real", to: "dashboard#real"

  get "dashboard/charts", to: "dashboard#charts"
  
  get "/login", to: "sesiones#new"
  
  post "/login", to: "sesiones#create"
  
  delete "/login", to: "sesiones#destroy"

  root 'dashboard#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(usuario)
    
    if usuario.rol? :administrador
      can :manage, :all
    end
    
    if usuario.rol? :usuario
      can :manage, :Dashboard
    end
    
    if usuario.rol? :gestor
      can :manage, :solicitudes
      can :manage, Solicitud

    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/auditoria.rb
class Auditoria < ActiveRecord::Base
  belongs_to :estado
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  scope :activo, -> { where(activo: true) }

  belongs_to :tasa
  belongs_to :permiso
  
end

app/models/concurso.rb
class Concurso < ActiveRecord::Base
  scope :activo, -> { where(activo: true) }

  validates :modelo_pdf, presence: true
            
  belongs_to :categoria
  belongs_to :convocatoria

  belongs_to :pago
  has_and_belongs_to_many :titulaciones
  has_and_belongs_to_many :zonas
  has_and_belongs_to_many :turnos

  belongs_to :tasa
  
  def con
    categoria.denominacion
  end
end

app/models/estado.rb
class Estado < ActiveRecord::Base
end

app/models/historico.rb
class Historico < ActiveRecord::Base      
  belongs_to :solicitud
  belongs_to :usuario
  belongs_to :estado
  has_and_belongs_to_many :motivos
  
  def motivos_rechazo
    motivos_array = Array.new
      motivos.each do |m|
        motivos_array << m.denominacion
      end
    motivos_array.join(", ")
  end
end

app/models/informix.rb
class Informix < ActiveRecord::Base      
  scope :activo, -> { where(activo: true) }
      
    validates :codigo, presence: true    
          

  belongs_to :concurso
  belongs_to :turno
end

app/models/menu.rb
class Menu < ActiveRecord::Base      
has_many :submenus
  scope :activo, -> { where(activo: true) }

end

app/models/motivo.rb
class Motivo < ActiveRecord::Base      
  scope :activo, -> { where(activo: true) }
      
    validates :denominacion, presence: true
    
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base      
  scope :activo, -> { where(activo: true) }
      
    validates :provincia, presence: true
    
      
    validates :habitantes, presence: true
    
      
    validates :denominacion, presence: true
    

  belongs_to :provincia
end

app/models/pago.rb
class Pago < ActiveRecord::Base
    has_one :solicitud
  def obtener_numero
    @OFFSET_CARTA_PAGO = "05307000001"
    id + @OFFSET_CARTA_PAGO.to_i
  end
  
  def obtener_digito_control
    modulo = obtener_numero % 7
    if modulo == 0
      0
    else
      7 - modulo
    end 
  end
end

app/models/permiso.rb
class Permiso < ActiveRecord::Base
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base      
  scope :activo, -> { where(activo: true) }
      
    validates :denominacion, presence: true
    

end

app/models/sexo.rb
class Sexo < ActiveRecord::Base
end

app/models/solicitud.rb
class Solicitud < ActiveRecord::Base      
  scope :activo, -> { where(activo: true) }
      
    validates :estado, presence: true
    
      
    validates :pago, presence: true
    
      
    validates :nif, presence: true
    
      
    validates :turno, presence: true
    
      
    validates :concurso, presence: true
    

  belongs_to :solicitud
  belongs_to :concurso
  belongs_to :turno
  belongs_to :pago
  belongs_to :estado
  belongs_to :municipio
  belongs_to :nacionalidad
  belongs_to :sexo
  belongs_to :titulacion
  belongs_to :permiso
  has_and_belongs_to_many :zonas
  has_and_belongs_to_many :motivos

end

app/models/submenu.rb
class Submenu < ActiveRecord::Base      
  scope :activo, -> { where(activo: true) }

  belongs_to :menu
end

app/models/tasa.rb
class Tasa < ActiveRecord::Base
end

app/models/titulacion.rb
class Titulacion < ActiveRecord::Base
  scope :activo, -> { where(activo: true) }

  has_many :concursos
  
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_secure_password

  paginates_per 10
  validates :nombre, presence: true
  validates :apellidos, presence: true
  validates :correo, presence: true
  validates :usuario, presence: true
  validates :correo, uniqueness: true
  validates :usuario, uniqueness: true

  scope :activo, -> { where(activo: true) }
  
  scope :con_rol, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0 "} }  

  ROLES = %w[usuario administrador gestor]

  def rol_symbols  
    roles.map(&:to_sym)  
  end  
  
  def roles=(roles)  
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum  
  end  
  
  def roles  
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }  
  end
  
  def rol?(rol)  
    roles.include? rol.to_s  
  end  
end

app/models/zona.rb
class Zona < ActiveRecord::Base
  has_many :solicitudes
end

app/controllers/submenus_controller.rb
class SubmenusController < ApplicationController
  before_action :requiere_autenticacion!  
  before_filter :set_submenu, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:create]

  def index
    @submenus = Submenu.activo.page params[:page]
  end
  
  def new
    @submenu = Submenu.new
  end
  
  def edit
  end
  
  def create
    @submenu = Submenu.new(submenu_params)
    if @submenu.save
      flash[:notice] = "Submenu añadida correctamente"
      redirect_to submenus_path
    else
      flash[:alert] = "Hubo un error al añadir el Submenu"
      render "new"
    end
  end

  def update
    if @submenu.update(submenu_params)
      flash[:notice] = "Submenu modificada correctamente"
      redirect_to submenus_path
    else
      flash[:alert] = "Hubo un error al modificar el Submenu"
      render "edit"
    end
  end
  
  def destroy
    @submenu.activo = false
    @submenu.save
    flash[:notice] = "Submenu borrada correctamente"
    redirect_to submenus_path
  end
  
  private
  def submenu_params
    params.require(:submenu).permit(:denominacion, :icono, :enlace, :menu_id, :activo)
  end
  
  def set_submenu
    @submenu = Submenu.activo.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Vaya, parece que ha habido un error al buscar esa Submenu"
    redirect_to submenus_path
  end
end

app/views/submenus/_boton_atras.html.erb
<div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to submenus_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Nuevo Submenu
          </button>
        <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/submenus/_boton_nuevo.html.erb
<div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to new_submenu_path do %>
        <button class="btn btn-primary btn-sm">
          <i class="icon-user"></i>
          Nuevo Submenu
        </button>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/submenus/_errores.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %>
    <% if @submenu.errors.any? %>
      <div id="error_explanation">
        <%= pluralize(@submenu.errors.count, "error") %>
          debe corregirse:
        <ul>
          <% @submenu.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

app/views/submenus/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header blue-background">
        <% if params[:action] == "new" %>
        <div class="title">Nuevo Submenu</div>
        <% else %>
        <div class="title">Editar Submenu</div>
        <% end %>
        <div class="actions">
          <a href="#" class="btn box-collapse btn-xs btn-link"><i></i>
          </a>
        </div>
      </div>
      <div class="box-content">        
        <%= form_for @submenu, :html => {:novalidate => 'novalidate', class: "form form-horizontal validate-form"} do |f| %>
        
          
            
              
                <div class="form-group">
                  <%= f.label :denominacion, class: "control-label col-sm-3 col-sm-3" %>
                  <div class="col-sm-4 controls">
                    <%= f.text_field :denominacion, class: "form-control", placeholder: "Introduce el denominacion", "data-rule-required" => "true", "data-rule-minlength" => "2" %>
                  </div>
                </div>
              
            
          
        
          
            
              
                <div class="form-group">
                  <%= f.label :icono, class: "control-label col-sm-3 col-sm-3" %>
                  <div class="col-sm-4 controls">
                    <%= f.text_field :icono, class: "form-control", placeholder: "Introduce el icono", "data-rule-required" => "true", "data-rule-minlength" => "2" %>
                  </div>
                </div>
              
            
          
        
          
            
              
                <div class="form-group">
                  <%= f.label :enlace, class: "control-label col-sm-3 col-sm-3" %>
                  <div class="col-sm-4 controls">
                    <%= f.text_field :enlace, class: "form-control", placeholder: "Introduce el enlace", "data-rule-required" => "true", "data-rule-minlength" => "2" %>
                  </div>
                </div>
              
            
          
        
          
            
              <div class="form-group">
                <%= f.label :menu_id, class: "control-label col-sm-3 col-sm-3" %>
                <div class="col-sm-4 controls">
                  <%= f.collection_select :menu_id, Menu.order(:denominacion),:id,:denominacion, {}, {:class => "form-control"} %>
                </div>
              </div>
            
          
        
          
            
              
            
          
        
        <div class="form-actions">
          <div class="row">
            <div class="col-sm-9 col-sm-offset-3">
              <%= f.submit class: "btn btn-primary" do %>
              <i class="icon-save"></i>            
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/submenus/_submenus.html.erb
<div class="row">
  <div class="col-sm-12">
    <div style="margin-bottom:0;" class="box bordered-box blue-border">
      <div class="box-header blue-background">
        <div class="title">Listado de Submenus</div>
        <div class="actions">
          <a href="#" class="btn box-collapse btn-xs btn-link"><i></i>
          </a>
        </div>
      </div>
      <div class="box-content box-no-padding">
        <div class="responsive-table">
          <div class="scrollable-area">
            <table class='data-table-column-filter table table-bordered table-striped'>
              <!-- we need thead because of ordering controls -->
              <thead>
                <tr>
                  <th width="10%">#</th>
                  
                    
                      <th>denominacion</th>
                    
                  
                    
                      <th>icono</th>
                    
                  
                    
                      <th>enlace</th>
                    
                  
                    
                      <th>menu</th>
                    
                  
                    
                  
                  <th width="11%">Acciones</th>
                </tr>
              </thead>
              <tbody>
                <% @submenus.each do |s| %>
                  <tr>
                    <td width="10%"><%= s.id %></td>
                    
                      
                        
                          <td><%= s.denominacion %></td>
                        
                      
                    
                      
                        
                          <td><%= s.icono %></td>
                        
                      
                    
                      
                        
                          <td><%= s.enlace %></td>
                        
                      
                    
                      
                        
                          <td><%= s.menu.denominacion %></td>                  
                        
                      
                    
                      
                    
                    <td width="11%">
                      <div class="text-right">                     
                      <%= link_to edit_submenu_path(s), id: "Editar", class: "btn btn-success btn-xs" do %> 
                        <i class="icon-edit"></i>
                      <% end %>
                      <%= link_to submenu_path(s), method: :delete, data: { confirm: "¿Seguro que quieres borrar esta Submenu?"}, id: "Borrar", class: "btn btn-danger btn-xs" do %>
                      <i class="icon-remove"></i>
                      <% end %>
                      </div>
                    </td>
                    </tr>
                  <% end %>                  
                </tbody>        
                <tfoot>
                  <tr>
                    <th>Id</th>
                    
                    
                      <th>denominacion</th>
                    
                  
                    
                      <th>icono</th>
                    
                  
                    
                      <th>enlace</th>
                    
                  
                    
                      <th>menu</th>
                    
                  
                    
                  
                     
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/submenus/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-edit"></i>
        <span>Submenus</span>
      </h1>
      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to submenus_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Atrás
          </button>
        <% end %>

      </div>
    </div>
  </div>
  </div>
</div>
  <%= render 'form' %>

app/views/submenus/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-table"></i>
        <span>Submenus</span>
      </h1>

      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <%= render "layouts/mensajes" %>
  <%= render "boton_nuevo" %>
</div>
  <%= render 'submenus' %>

app/views/submenus/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-edit"></i>
        <span>Submenus</span>
      </h1>
      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to submenus_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Atrás
          </button>
        <% end %>

      </div>
    </div>
  </div>
  </div>
</div>
  <%= render 'form' %>