config/routes.rb
Sidemura::Application.routes.draw do  

  resources :informixes
  
  resources :motivos
  
  resources :convocatorias
 
  resources :concursos  

  resources :categorias  
  
  resources :titulaciones
  
  get "solicitudes/verificar/:id", to: "solicitudes#verificar_solicitud"
  
  get "solicitudes/verificar", to: "solicitudes#verificar"
 
  get "solicitudes/actualizar_concurso", to: "solicitudes#actualizar_concurso"

  post "solicitudes/verificar", to: "solicitudes#validar"

  post "solicitudes/rechazar", to: "solicitudes#rechazar"
  
  get "solicitudes/ficheros", to: "solicitudes#ficheros"

  post "solicitudes/ficheros", to: "solicitudes#add_ficheros"
  
  post "solicitudes/add_pdf", to: "solicitudes#add_pdf"
  
  get "solicitudes/imprimir/:grupo/:concurso/:turno/:estado", to: "solicitudes#imprimir"

  get 'solicitudes/actualiza_municipios/:id', to: 'solicitudes#actualiza_municipios'

  get 'solicitudes/actualiza_titulaciones/:id', to: 'solicitudes#actualiza_titulaciones'
  
  get 'solicitudes/actualiza_tasas/:id', to: 'solicitudes#actualiza_tasas'

  get 'solicitudes/actualiza_codigo_categoria/:id/:subid', to: 'solicitudes#actualiza_codigo_categoria'
  
  resources :solicitudes
    
  resources :tipologias
  
  resources :municipios 

  resources :provincias
 
  resources :submenus
  
  resources :menus  
  
  resources :usuarios

  get "dashboard/", to: "dashboard#index"

  get "dashboard/real", to: "dashboard#real"

  get "dashboard/charts", to: "dashboard#charts"
  
  get "/login", to: "sesiones#new"
  
  post "/login", to: "sesiones#create"
  
  delete "/login", to: "sesiones#destroy"

  root 'dashboard#index'

  

end

app/models/concurso.rb
class Concurso < ActiveRecord::Base
  scope :activo, -> { where(activo: true) }

  validates :modelo_pdf, presence: true
            
  belongs_to :categoria
  belongs_to :convocatoria

  belongs_to :pago
  has_and_belongs_to_many :titulaciones
  has_and_belongs_to_many :zonas
  has_and_belongs_to_many :turnos

  belongs_to :tasa
  
  def con
    categoria.denominacion
  end
end

app/controllers/concursos_controller.rb
class ConcursosController < ApplicationController
  before_action :requiere_autenticacion!  
  before_filter :set_concurso, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:create]

  def index
    @concursos = Concurso.activo.page params[:page]
    respond_to do |format|
      format.html
      format.json { render json: ConcursosDatatable.new(view_context) }
    end
  end
  
  def new
    @concurso = Concurso.new
    @titulaciones = Titulacion.all
  end
  
  def edit
  end
  
  def create
    @concurso = Concurso.new(concurso_params)
    if @concurso.save
      if params[:turnos]
        @turnos = params[:turnos]         
        @turnos.each do |t|
          turno = Turno.find(t)
          @concurso.turnos << turno
        end
      end
      if params[:titulaciones]
        @titulaciones = params[:titulaciones]         
        @titulaciones.each do |t|
          titulacion = Titulacion.find(t)
          @concurso.titulaciones << titulacion
        end
      end
      if params[:zonas]
        @zonas = params[:zonas]         
        @zonas.each do |t|
          zona = Zona.find(t)
          @concurso.zonas << zona
        end
      else
        (1..16).each do |t|
          zona = Zona.find(t)
          @concurso.zonas << zona
        end
      end
      
      if params[:turnos]
        @turnos = params[:turnos]         
        @turnos.each do |t|
          informix = Informix.new
          informix.concurso_id = @concurso.id
          informix.turno_id = t
          informix.codigo = params[:categoria_informix]
          Rails.logger.info "Categoría es #{@concurso.id}"
          Rails.logger.info "Turno es #{t}"
          Rails.logger.info "Parámetro categoria_informix es #{params[:categoria_informix]}"
          informix.save          
        end
      end
      
     
      flash[:notice] = "Concurso añadido correctamente"
      redirect_to concursos_path
    else
      flash[:alert] = "Hubo un error al añadir el Concurso"
      render "new"
    end
  end

  def update
    if @concurso.update(concurso_params)
      if params[:turnos]
        @concurso.turnos.destroy_all
        @turnos = params[:turnos]         
        @turnos.each do |t|
          turno = Turno.find(t)
          @concurso.turnos << turno
        end
      end
      if params[:titulaciones]
        @concurso.titulaciones.destroy_all
        @titulaciones = params[:titulaciones]         
        @titulaciones.each do |t|
          titulacion = Titulacion.find(t)
          @concurso.titulaciones << titulacion
        end
      end
      if params[:zonas]
        @concurso.zonas.destroy_all
        @zonas = params[:zonas]         
        @zonas.each do |t|
          zona = Zona.find(t)
          @concurso.zonas << zona
        end
      end
      flash[:notice] = "Concurso modificado correctamente"
      redirect_to concursos_path
    else
      flash[:alert] = "Hubo un error al modificar el Concurso"
      render "edit"
    end
  end
  
  def destroy
    @concurso.activo = false
    @concurso.save
    flash[:notice] = "Concurso borrada correctamente"
    redirect_to concursos_path
  end
  
  private
  def concurso_params
    params.require(:concurso).permit(:fecha_doe, :categoria_id, :tasa_id, :modelo_pdf, :titulaciones, :zonas)
  end
  
  def set_concurso
    @concurso = Concurso.activo.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Vaya, parece que ha habido un error al buscar esa Concurso"
    redirect_to concursos_path
  end
end

app/helpers/concursos_helper.rb
module ConcursosHelper
  def boton_concurso
    Submenu.where(enlace: "/concursos").last.icono
  end
end

app/views/concursos/_boton_atras.html.erb
<div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to convocatorias_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Nuevo Convocatoria
          </button>
        <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/concursos/_boton_nuevo.html.erb
<div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to new_concurso_path do %>
        <button class="btn btn-primary btn-sm">
          <i class="<%= boton_concurso%>"></i>
          Nuevo Concurso
        </button>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/concursos/_concursos.html.erb
<div class="row">
  <div class="col-sm-12">
    <div style="margin-bottom:0;" class="box bordered-box blue-border">
      <div class="box-header blue-background">
        <div class="title">Listado de Concursos</div>
        <div class="actions">
          <a href="#" class="btn box-collapse btn-xs btn-link"><i></i>
          </a>
        </div>
      </div>
      <div class="box-content box-no-padding">
        <div class="responsive-table">
          <div class="scrollable-area">

            <table id="concursos" class='data-table-column-filter table table-bordered table-striped dataTable' data-source="<%= concursos_url(format: "json") %>">
                   <!-- we need thead because of ordering controls -->
                   <thead>
                <tr>
                  <th width="10%">#</th>
                  
                    
                      <th>Convocatoria</th>
                    
                  
                    
                      <th>Categoría</th>
                    
                  
                    
                      <th>Tasa</th>
                    
                  
                    
                      <th>Modelo PDF</th>
                    
                  
                  <th width="11%">Acciones</th>
                </tr>             
              </thead>
              <tbody>
                <% @concursos.each do |e| %>
                <tr>
                  <td width="10%"><%= e.id %></td>
                  
                    
                      <td><%= e.convocatoria.fecha_doe.strftime("%d-%m-%Y")%></td>
                      
                    
                    
                      <td><%= e.categoria.denominacion %></td>
                      
                    
                    
                      <td><%= e.categoria.tasa.denominacion %></td>
                      
                    
                    
                      <td><%= e.modelo_pdf%></td>
                      
                    
                  <td width="11%">
                    <div class="text-right">                     
                      <a id="Editar" href="/concursos/<%= e.id %>/edit" class="btn btn-success btn-xs"> 
                         <i class="icon-edit"></i>
                      </a> 
                      <a rel="nofollow" id="Borrar" href="/concursos/<%= e.id %>" data-method="delete" data-confirm="¿Seguro que quieres borrar este Concurso?" class="btn btn-danger btn-xs">
                         <i class="icon-remove"></i>
                      </a>
                    </div>

                  </td>
                </tr>
                <% end %>
              </tbody>       
              <tfoot>
                <tr>
                  <th>Id</th>
                  
                    
                      <th>fecha_doe</th>
                    
                  
                    
                      <th>categoria</th>
                    
                  
                    
                      <th>tasa</th>
                    
                  
                    
                      <th>modelo_pdf</th>
                    
                  
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/concursos/_errores.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %>
    <% if @convocatoria.errors.any? %>
      <div id="error_explanation">
        <%= pluralize(@convocatoria.errors.count, "error") %>
          debe corregirse:
        <ul>
          <% @convocatoria.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

app/views/concursos/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header blue-background">
        <% if params[:action] == "new" %>
        <div class="title">Nuevo Concurso</div>
        <% else %>
        <div class="title">Editar Concurso</div>
        <% end %>
        <div class="actions">
          <a href="#" class="btn box-collapse btn-xs btn-link"><i></i>
          </a>
        </div>
      </div>
      <div class="box-content">        
        <%= form_for @concurso, :html => {id: "new_concurso", class: "form form-horizontal"} do |f| %>
                               
                
              <div class="form-group">
                <%= f.label :convocatoria_id, class: "control-label col-sm-3 col-sm-3" %>
                <div class="col-sm-4 controls">
                  <%= f.collection_select :convocatoria_id, Convocatoria.order(:denominacion),:id,:denominacion, {}, {:class => "form-control"} %>
                </div>
              </div>
            
              <div class="form-group">
                <%= f.label :turno_id, class: "control-label col-sm-3 col-sm-3" %>
                <div class="col-sm-4 controls">
                  <% Turno.all.each do |t| %>
                    
                      <%= check_box_tag("turnos[]", t.id,@concurso.turnos.include?(t)) %> <%= t.denominacion %>
                  <% end %>
                </div>
              </div>
        
              <div class="form-group">
                <%= f.label :categoria_id, "Categoría", class: "control-label col-sm-3 col-sm-3" %>
                <div class="col-sm-4 controls">
                  <%= f.collection_select :categoria_id, Categoria.order(:denominacion),:id,:denominacion, {}, {:class => "form-control"} %>
                </div>
              </div>
          
              <div class="form-group">
                <%= f.label :categoria_informix, "Categoría Informix", class: "control-label col-sm-3 col-sm-3" %>
                <div class="col-sm-4 controls">
                  <%= text_field_tag :categoria_informix,nil, class: "form-control", placeholder: "Introduce la Categoría de INFORMIX" %>

                </div>
              </div>
                            
                <div class="form-group">
                  <%= f.label :modelo_pdf, class: "control-label col-sm-3 col-sm-3" %>
                  <div class="col-sm-4 controls">
                    <%= f.number_field :modelo_pdf, class: "form-control", placeholder: "Introduce el modelo_pdf" %>
                  </div>
                </div>
              <div class="form-group">
                <div class="col-sm-3 controls">
                </div>
                <div class="col-sm-4 controls">

              <div id="tabla_titulaciones">             
                <% if params[:action] == "edit" %>
                  <% @concurso.titulaciones.each do |t| %>
                <div class="alert alert-info alert-dismissable"><a href="#" data-dismiss="alert" class="close">×</a><i class="icon-circle-blank"></i> <%= t.denominacion %><input type="hidden" name="titulaciones[]" value="<%= t.id %>"></div>
                  <% end %>
                <% end %>
              </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :titulacion, class: "control-label col-sm-3 col-sm-3" %>
                <div class="col-sm-4 controls">
                  <%= collection_select :titulacion,:id, Titulacion.order(:denominacion),:id,:denominacion, {:prompt => 'Selecciona las titulaciones'}, {:class => "form-control select2 select2-with-searchbox"} %>
                </div>
              </div>
          
              <div class="form-group">
                <div class="col-sm-3 controls">
                </div>
                <div class="col-sm-4 controls">

              <div id="tabla_zonas">
                <% if params[:action] == "edit" %>
                  <% @concurso.zonas.each do |t| %>
                <div class="alert alert-warning alert-dismissable"><a href="#" data-dismiss="alert" class="close">×</a><i class="icon-circle-blank"></i> <%= t.denominacion %><input type="hidden" name="zonas[]" value="<%= t.id %>"></div>
                  <% end %>
                <% end %>              
              </div>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :zona, class: "control-label col-sm-3 col-sm-3" %>
                <div class="col-sm-4 controls">
                  <%= collection_select :zona,:id, Zona.order(:id),:id,:denominacion, {:prompt => 'Selecciona las zonas'}, {:class => "form-control select2 select2-with-searchbox"} %>
                </div>
              </div>
             
        
        
        <div class="form-actions">
          <div class="row">
            <div class="col-sm-9 col-sm-offset-3">
              <%= f.submit class: "btn btn-primary" do %>
              <i class="icon-save"></i>            
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <%= render 'titulaciones' %>
    </div>
  </div>
</div>

app/views/concursos/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-edit"></i>
        <span>Concursos</span>
      </h1>
      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <%= render 'errores' %>
  <div class="box">
    <div class="box-content">
      <div class="btn-toolbar">
        <div class="btn-group dropdown">

          <%= link_to concursos_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Atrás
          </button>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>
  <%= render 'form' %>

app/views/concursos/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-table"></i>
        <span>Concursos</span>
      </h1>

      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <%= render "layouts/mensajes" %>
  <%= render "boton_nuevo" %>
</div>
  <%= render 'concursos' %>

app/views/concursos/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-edit"></i>
        <span>Concurso</span>
      </h1>
      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>  
  <%= render 'errores' %>
  <div class="box">
    <div class="box-content">
      <div class="btn-toolbar">
        <div class="btn-group dropdown">

          <%= link_to concursos_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Atrás
          </button>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>
  <%= render 'form' %>