config/routes.rb
Sidemura::Application.routes.draw do  

  resources :informixes
  
  resources :motivos
  
  resources :convocatorias
 
  resources :concursos  

  resources :categorias  
  
  resources :titulaciones
  
  get "solicitudes/verificar/:id", to: "solicitudes#verificar_solicitud"
  
  get "solicitudes/verificar", to: "solicitudes#verificar"
 
  get "solicitudes/actualizar_concurso", to: "solicitudes#actualizar_concurso"

  post "solicitudes/verificar", to: "solicitudes#validar"

  post "solicitudes/rechazar", to: "solicitudes#rechazar"
  
  get "solicitudes/ficheros", to: "solicitudes#ficheros"

  post "solicitudes/ficheros", to: "solicitudes#add_ficheros"
  
  post "solicitudes/add_pdf", to: "solicitudes#add_pdf"
  
  get "solicitudes/imprimir/:grupo/:concurso/:turno/:estado", to: "solicitudes#imprimir"

  get 'solicitudes/actualiza_municipios/:id', to: 'solicitudes#actualiza_municipios'

  get 'solicitudes/actualiza_titulaciones/:id', to: 'solicitudes#actualiza_titulaciones'
  
  get 'solicitudes/actualiza_tasas/:id', to: 'solicitudes#actualiza_tasas'

  get 'solicitudes/actualiza_codigo_categoria/:id/:subid', to: 'solicitudes#actualiza_codigo_categoria'
  
  resources :solicitudes
    
  resources :tipologias
  
  resources :municipios 

  resources :provincias
 
  resources :submenus
  
  resources :menus  
  
  resources :usuarios

  get "dashboard/", to: "dashboard#index"

  get "dashboard/real", to: "dashboard#real"

  get "dashboard/charts", to: "dashboard#charts"
  
  get "/login", to: "sesiones#new"
  
  post "/login", to: "sesiones#create"
  
  delete "/login", to: "sesiones#destroy"

  root 'dashboard#index'

  

end

app/models/provincia.rb
class Provincia < ActiveRecord::Base      
  scope :activo, -> { where(activo: true) }
      
    validates :denominacion, presence: true
    

end

app/controllers/provincias_controller.rb
class ProvinciasController < ApplicationController
  before_action :requiere_autenticacion!  
  before_filter :set_provincia, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:create]

  def index
    @provincias = Provincia.activo.page params[:page]
    respond_to do |format|
      format.html
      format.json { render json: ProvinciasDatatable.new(view_context) }
    end
  end
  
  def new
    @provincia = Provincia.new
  end
  
  def edit
  end
  
  def create
    @provincia = Provincia.new(provincia_params)
    if @provincia.save
      flash[:notice] = "Provincia añadida correctamente"
      redirect_to provincias_path
    else
      flash[:alert] = "Hubo un error al añadir el Provincia"
      render "new"
    end
  end

  def update
    if @provincia.update(provincia_params)
      flash[:notice] = "Provincia modificada correctamente"
      redirect_to provincias_path
    else
      flash[:alert] = "Hubo un error al modificar el Provincia"
      render "edit"
    end
  end
  
  def destroy
    @provincia.activo = false
    @provincia.save
    flash[:notice] = "Provincia borrada correctamente"
    redirect_to provincias_path
  end
  
  private
  def provincia_params
    params.require(:provincia).permit(:denominacion, :activo)
  end
  
  def set_provincia
    @provincia = Provincia.activo.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Vaya, parece que ha habido un error al buscar esa Provincia"
    redirect_to provincias_path
  end
end

app/helpers/provincias_helper.rb
module ProvinciasHelper
  def boton_provincia
    Submenu.where(enlace: "/provincias").last.icono
  end
end

app/views/provincias/_boton_atras.html.erb
<div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to provincias_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Nuevo Provincia
          </button>
        <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/provincias/_boton_nuevo.html.erb
<div class="box">
  <div class="box-content">
    <div class="btn-toolbar">
      <div class="btn-group dropdown">

        <%= link_to new_provincia_path do %>
        <button class="btn btn-primary btn-sm">
          <i class="<%= boton_provincia %>"></i>
          Nuevo Provincia
        </button>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/provincias/_errores.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= flash[:alert] %>
    <% if @provincia.errors.any? %>
      <div id="error_explanation">
        <%= pluralize(@provincia.errors.count, "error") %>
          debe corregirse:
        <ul>
          <% @provincia.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>

app/views/provincias/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header blue-background">
        <% if params[:action] == "new" %>
        <div class="title">Nuevo Provincia</div>
        <% else %>
        <div class="title">Editar Provincia</div>
        <% end %>
        <div class="actions">
          <a href="#" class="btn box-collapse btn-xs btn-link"><i></i>
          </a>
        </div>
      </div>
      <div class="box-content">        
        <%= form_for @provincia, :html => {:novalidate => 'novalidate', class: "form form-horizontal validate-form"} do |f| %>
        
          
            
              
                <div class="form-group">
                  <%= f.label :denominacion, class: "control-label col-sm-3 col-sm-3" %>
                  <div class="col-sm-4 controls">
                    <%= f.text_field :denominacion, class: "form-control", placeholder: "Introduce el denominacion", "data-rule-required" => "true", "data-rule-minlength" => "2" %>
                  </div>
                </div>
              
            
          
        
          
            
              
            
          
        
        <div class="form-actions">
          <div class="row">
            <div class="col-sm-9 col-sm-offset-3">
              <%= f.submit class: "btn btn-primary" do %>
              <i class="icon-save"></i>            
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/provincias/_provincias.html.erb
<div class="row">
  <div class="col-sm-12">
    <div style="margin-bottom:0;" class="box bordered-box blue-border">
      <div class="box-header blue-background">
        <div class="title">Listado de Provincias</div>
        <div class="actions">
          <a href="#" class="btn box-collapse btn-xs btn-link"><i></i>
          </a>
        </div>
      </div>
      <div class="box-content box-no-padding">
        <div class="responsive-table">
          <div class="scrollable-area">

            <table id="provincias" class='data-table-column-filter table table-bordered table-striped dataTable' data-source="<%= provincias_url(format: "json") %>">
                   <!-- we need thead because of ordering controls -->
                   <thead>
                <tr>
                  <th width="10%">#</th>
                  
                    
                      <th>denominacion</th>
                    
                  
                    
                  
                  <th width="11%">Acciones</th>
                </tr>             
              </thead>
              <tbody>
                <% @provincias.each do |e| %>
                <tr>
                  <td width="10%"><%= e.id %></td>
                  
                    
                      <td><%= e.denominacion%></td>
                      
                    
                    
                    
                  <td width="11%">
                    <div class="text-right">                     
                      <a id="Editar" href="/provincias/<%= e.id %>/edit" class="btn btn-success btn-xs"> 
                         <i class="icon-edit"></i>
                      </a> 
                      <a rel="nofollow" id="Borrar" href="/provincias/<%= e.id %>" data-method="delete" data-confirm="¿Seguro que quieres borrar este Provincia?" class="btn btn-danger btn-xs">
                         <i class="icon-remove"></i>
                      </a>
                    </div>

                  </td>
                </tr>
                <% end %>
              </tbody>       
              <tfoot>
                <tr>
                  <th>Id</th>
                  
                    
                      <th>denominacion</th>
                    
                  
                    
                  
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/provincias/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-edit"></i>
        <span>Provincias</span>
      </h1>
      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <%= render 'errores' %>
  <div class="box">
    <div class="box-content">
      <div class="btn-toolbar">
        <div class="btn-group dropdown">

          <%= link_to provincias_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Atrás
          </button>
          <% end %>

        </div>
      </div>
    </div>
  </div>
  <%= render 'form' %>
</div>

app/views/provincias/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-table"></i>
        <span>Provincias</span>
      </h1>

      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>
  <%= render "layouts/mensajes" %>
  <%= render "boton_nuevo" %>
</div>
  <%= render 'provincias' %>

app/views/provincias/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header">

      <!-- page title -->
      <h1 class="pull-left">
        <i class="icon-edit"></i>
        <span>Provincias</span>
      </h1>
      <!-- breadcrumbs -->
      <%= render 'layouts/miguitas' %>
    </div>
  </div>  
  <%= render 'errores' %>
  <div class="box">
    <div class="box-content">
      <div class="btn-toolbar">
        <div class="btn-group dropdown">

          <%= link_to provincias_path do %>
          <button class="btn btn-primary btn-sm">
            <i class="icon-mail-reply"></i>
            Atrás
          </button>
          <% end %>

        </div>
      </div>
    </div>
  </div>
  <%= render 'form' %>
</div>